### PR TITLE
Objective-C support

### PR DESCRIPTION
**Pull request by krzysztofzablocki**

### CODE REVIEW

**Comment by jcislinsky** [comment]
In Obj-c class that implements protocol `LifetimeTrackable` Xcode says `Method definition for 'trackLifetime' not found` and at run app crashes.

Following Swift extension isn't bridged to objc as expected:
```
public extension LifetimeTrackable {	
    func trackLifetime() {
        LifetimeTracker.instance?.track(self, configuration: type(of: self).lifetimeConfiguration)
    }
}

**Comment by jcislinsky** [comment]
From obj-c AppDelegate I am not able to activate integration (in Swift `LifetimeTracker.setup(onUpdate: LifetimeTrackerDashboardIntegration(visibility: .visibleWithIssuesDetected).refreshUI)`).

In my verbose solution there was bridged func `[LifetimeConfiguration defaultSetup]`.

**Comment by krzysztofzablocki** [comment]
@jcislinsky how about now?

**Comment by krzysztofzablocki** [comment]
@jcislinsky fixed, also added sample objc project. Thanks for contributing!

**Pull request merged**
