### PR TITLE
Add SPM support for included UI elements

### PR DESCRIPTION
**Pull request by ltsuchiya**
This PR seeks to enable the LifetimeTracker UI elements in SPM builds. Currently attempting to use `LifetimeTrackerDashboardIntegration` will result in a crash.

Main changes:
- Bump swift-tools to 5.3
- Move storyboards and xibs into resources and specify the resources folder in Swift.package
- Add Bundle extension to handle logic for SPM vs. non-SPM usage
- Ensure that all storyboards have `customModuleProvider="target"` removed (Inherit module from target)
- Ensure that all storyboards have `customModule="LifetimeTracker"` set

Will still need to be tested for non-SPM usage.

### CODE REVIEW

**Review by krzysztofzablocki — APPROVED** [review]
thanks for contributing🙇

**Comment by ltsuchiya** [comment]
@krzysztofzablocki Thanks for merging so quickly. When you get a chance could you bump up a new git tagged version? That should allow the SPM users who are using version control to update.

**Comment by krzysztofzablocki** [comment]
done with 1.8.1 @ltsuchiya

**Comment by ltsuchiya** [comment]
@krzysztofzablocki Thanks! 🙏

**Pull request merged**
